name: MISP-Collector Docker Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Fetch required Go modules
      run:  go mod download

    - name: Build Binary
      run: go build -v .

    - name: Install Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: AtlasInsideCorp
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      uses: docker/build-push-action@v2
      with:
          context: /home/runner/work/UTMStackDatasourcesMISP/UTMStackDatasourcesMISP/
          push: true
          tags: ghcr.io/atlasinsidecorp/mispcollector:v9